version: '3.7'

services:

  mongo:
    image : 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../db/mongodb:/db_data/

  sqlite3:
    image: 'nouchka/sqlite3:latest'
    container_name: 'sqlite'
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ../db/sqlite:/root/db/

  web:
    build:
      context: ..
      dockerfile: ./web/Dockerfile
    container_name: 'web'
    ports:
      - "8000:8000"
    volumes:
      - ../web/:/src
    command: /bin/sh -c "sleep 10; python -u manager.py runserver 0.0.0.0:8000"

  # nginx:
  #   build:
  #     context: ..
  #     dockerfile: ./nginx/Dockerfile
  #   container_name: 'nginx'
  #   ports:
  #     - 80:80
  #     - 443:443
