version: '3.7'

services:

  mongo:
    image : mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../db/mongodb:/db_data/

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ../db/sql/backup:/docker-entrypoint-initdb.d

  web:
    build:
      context: ..
      dockerfile: ./web/Dockerfile
    container_name: 'web'
    ports:
      - "8000:8000"
    volumes:
      - ../web/:/src
    command: /bin/sh -c "sleep 10; python manage.py migrate && python -u manage.py runserver_plus 0.0.0.0:8000 --cert-file certificate/app.crt --key-file certificate/app.key"