version: '3.7'

services:

  mongo:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
    - /home/barry/mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  