version: '3.7'

services:

  mongo:
    image : 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../db/mongodb:/db_data/

  sqlite3:
    image: 'nouchka/sqlite3:latest'
    stdin_open: true
    tty: true
    volumes:
      - ./db/sqllite:/root/db/

  front:
    build:
      context: ..
      dockerfile: ./front/Dockerfile
    container_name: 'front'
    ports:
      - 8080:8080
    volumes:
      - ../front/:/src
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  back:
    build:
      context: ..
      dockerfile: ./back/Dockerfile
    container_name: 'back'
    ports:
      - 8081:8081
    volumes:
      - ../back/:/src
    command: /bin/sh -c "while sleep 1000; do :; done"

  # nginx:
  #   build:
  #     context: ..
  #     dockerfile: ./nginx/Dockerfile
  #   container_name: 'nginx'
  #   ports:
  #     - 80:80
  #     - 443:443
